/***********************************************************************/
/*                                                                     */
/*  FILE        :task04-1.c                                            */
/*  DATE        :Mon, Oct 30, 2017                                     */
/*  DESCRIPTION :Main Program                                          */
/*  CPU TYPE    :H8/3052F                                              */
/*                                                                     */
/*  This file is generated by Renesas Project Generator (Ver.4.16).    */
/*                                                                     */
/***********************************************************************/

#include "iodefine.h"
#include "conv.h"
#include "lcd.h"
#include "rsctl.h"
#pragma interrupt INT_IMIA2(vect=32)

long max_period = 0xFFFF;
long now_period = 0xFFFF;

void INT_IMIA2(void) {
    ITU2.TSR.BIT.IMFA = 0;          // フラグ初期化
    now_period = ITU2.GRA;
    if(max_period > now_period && now_period != 0){
        max_period = now_period;
    }
}

double gra2ppm(long period){
    return 1 / ( ((double)period + 1) * 0.32 / 1000000 );
}

void main(void)
{
    char str[17];
    double now, max;
    int mode = 0;
    
    P4.DDR = 0x03;              // DCモーター IN1, 2
    P4.DR.BYTE = 0x03;          // 初期状態ブレーキ
    
    PA.DDR = 0x00;                      // SW0~4
    
    ITU1.TCR.BYTE = 0x23;               // GRAコンペアマッチ TCNTクリア 1/8クロック
    ITU.TMDR.BIT.PWM1 = 1;              // チャネル0 PWMモード
    ITU1.GRA = 0;
    ITU1.GRB = 400;
    ITU.TSTR.BIT.STR1 = 1;              // PWM運転開始
    
    ITU2.TCR.BIT.CCLR = 1;              // TCNT2はICでクリア
    ITU2.TCR.BIT.TPSC = 3;              // 1/8クロック
    ITU2.TIOR.BIT.IOA = 5;              // 立ち上がりでICを起こす
    ITU2.TIER.BIT.IMIEA = 1;            // GRA2のICで割り込み許可
    
    ITU.TSTR.BIT.STR2 = 1;              // タイマー開始
    
    init_lcd();                         // LCD初期化
    clear_lcd();                        // LCD画面リセット
    
    while(PA.DR.BIT.B0);                // SW0が押されるまで待機
    
    P4.DR.BYTE = 0x01;                  // DCモーター運転開始
    
    while(1){
        if(!PA.DR.BIT.B1){
            mode = 1;
            ITU1.GRA = 800;
        }
        
        max = gra2ppm(max_period);
        
        locate_lcd(0, 0);		        // LCD1行目にカーソルを移動
        dtoa(max, 2, str);              // 取り込んだ値をPPM文字列に変換
        lcd_prints(str);                // LCDに文字列を表示
        lcd_prints("  ");            // LCDの不要部分を上書き
        
        if(1000.0 < max){               // 最大値がバグったら
            max_period = 0xFFFF;        // 初期化    
        }
        
        if(mode != 0){
            now = gra2ppm(now_period);
        
            locate_lcd(0, 1);		    // LCD1行目にカーソルを移動
            dtoa(now, 2, str);          // 取り込んだ値をPPM文字列に変換
            lcd_prints(str);            // LCDに文字列を表示
            lcd_prints("  ");        // LCDの不要部分を上書き
            
            if((max/3) < now){          // 目標速度より速い
                ITU1.GRA = ITU1.GRA + 1;// GRA + 1
            }
            else if((max/3) > now){     // 目標速度より遅い
                ITU1.GRA = ITU1.GRA - 1;// GRA + 1
            }
            
            locate_lcd(8, 1);		    // LCD1行目にカーソルを移動
            ltoa(ITU1.GRA, str);        // 取り込んだ値をPPM文字列に変換
            lcd_prints(str);            // LCDに文字列を表示
            lcd_prints("  ");        // LCDの不要部分を上書き
        }
    }
}
