/***********************************************************************/
/*                                                                     */
/*  FILE        :task04-2.c                                            */
/*  DATE        :Mon, Oct 30, 2017                                     */
/*  DESCRIPTION :Main Program                                          */
/*  CPU TYPE    :H8/3052F                                              */
/*                                                                     */
/*  This file is generated by Renesas Project Generator (Ver.4.16).    */
/*                                                                     */
/***********************************************************************/
#include <string.h>

#include "iodefine.h"
#include "conv.h"
#include "lcd.h"
#include "rsctl.h"

#pragma interrupt INT_IMIA0(vect=24)
#pragma interrupt INT_IMIA2(vect=32)

int t = 0x80;                   // タイマー
int c = 0x80;                   // カウンター
long period = 0x7FFF;

void INT_IMIA0(void) {
    ITU0.TSR.BIT.IMFA = 0;      // フラグ初期化
    t++;
}

void INT_IMIA2(void) {
    ITU2.TSR.BIT.IMFA = 0;      // フラグ初期化
    c++;
    period = ITU2.GRA;
}

void main(void)
{
    char str[17];
    double tmp;
    int i, time;
    
    // ポート初期化
    P4.DDR = 0x03;                  // DCモーター IN1, 2
    P4.DR.BYTE = 0x03;              // 初期状態ブレーキ
    
    PA.DDR = 0x00;                  // SW0~4
    
    // タイマー初期化
    ITU0.TCR.BIT.CCLR = 1;          // TCNT0はICでクリア
    ITU0.TCR.BIT.TPSC = 3;          // 1/8クロック
    ITU0.GRA = 31249;               // 10[ms]
    ITU0.TIER.BIT.IMIEA = 1;        // GRA0のICで割り込み許可
    
    // PWM初期化
    ITU1.TCR.BYTE = 0x23;           // GRAコンペアマッチ TCNTクリア 1/8クロック
    ITU.TMDR.BIT.PWM1 = 1;          // チャネル0 PWMモード
    ITU1.GRA = 5000;
    ITU1.GRB = 5001;
    
    // インプットキャプチャ初期化
    ITU2.TCR.BIT.CCLR = 1;          // TCNT2はICでクリア
    ITU2.TCR.BIT.TPSC = 3;          // 1/8クロック
    ITU2.TIOR.BIT.IOA = 5;          // 立ち上がりでICを起こす
    ITU2.TIER.BIT.IMIEA = 1;        // GRA2のICで割り込み許可
    
    // LCD初期化
    init_lcd();                     // LCD初期化
    clear_lcd();                    // LCD画面リセット
    
    // シリアル初期化
	initSCI1(BR9600);               // ボーレート
    
    // タイマースタート
    ITU.TSTR.BIT.STR0 = 1;          // タイマースタート
    ITU.TSTR.BIT.STR1 = 1;          // PWM制御開始
    ITU.TSTR.BIT.STR2 = 1;          // カウンタスタート
    
    // GRB初期値算出
    P4.DR.BYTE = 0x01;              // DCモーター運転開始
    c = 0;                          // カウントリセット

    while(c < 10);                  // 10パルス分待機
    
    tmp = 1 / ( ((double)period + 1) * 0.32 / 1000000 );
                                    // pps計算
    tmp = 1000 / tmp * 1000;        // 1000p経過の必要時間計算
    
    ITU1.GRA = 5000;
    ITU1.GRB = 5000 + (((int)tmp - 5000) * 2);
    
    ITU.TSTR.BIT.STR1 = 1;          // PWM制御開始
    
    // メインループ
    while(1){
    
        P4.DR.BYTE = 0x00;          // DCモーター運転停止
        
        while(PA.DR.BIT.B0);        // SW0が押されるまで待機
    
        P4.DR.BYTE = 0x01;          // DCモーター運転開始
        
        t = 0;                      // タイマーリセット
        c = 0;                      // カウントリセット
        
        // 5sで1000p
        do{
            t = 0;                  // タイマーリセット
            c = 0;                  // カウントリセット
            
            // GRB 表示
            locate_lcd(0, 1);   // LCD2行目にカーソルを移動
            itoa(ITU1.GRB, str);// 取り込んだ値を文字列に変換
            lcd_prints(str);    // LCDに文字列を表示
            lcd_prints(" ");    // LCDの不要部分を上書き
            SCI1_OUT_s(str);	// シリアルポートに文字列を送信
            
            while(c < 1000);    // 1000カウントでストップ
            
            time = t;           // 経過時間取得
            
            i = (time - 500) * (time/10 - 50);
        
            if(time > 500){
                ITU1.GRB = ITU1.GRB + i;
            }else{
                ITU1.GRB = ITU1.GRB - i;
            }
            
            // 経過秒数編集
            itoa(time, str);    // 取り込んだ値を文字列に変換
            for(i = 0; i < 14; i++){
                if(str[i] == '\0'){
                    str[i]   = '0';
                    str[i+1] = 'm';
                    str[i+2] = 's';
                    str[i+3] = '\0';
                    break;
                }
            }
    
            // 経過秒数表示
            locate_lcd(0, 0);   // LCD1行目にカーソルを移動
            lcd_prints(str);    // LCDに文字列を表示
            lcd_prints(" ");    // LCDの不要部分を上書き
            SCI1_OUT_s(str);	// シリアルポートに文字列を送信
        }while( time < 495 || 505 < time);
    }
}
