/***********************************************************************/
/*                                                                     */
/*  FILE        :task02.c                                               */
/*  DATE        :Mon, Oct 06, 2017                                     */
/*  DESCRIPTION :Main Program                                          */
/*  CPU TYPE    :H8/3052F                                              */
/*                                                                     */
/*  This file is generated by Renesas Project Generator (Ver.4.16).    */
/*                                                                     */
/***********************************************************************/

#include "iodefine.h"
#include "conv.h"
#include "lcd.h"
#include "rsctl.h"
#pragma interrupt INT_IMIA0(vect=24)

unsigned int c = 0x8fff;
unsigned char md[] = {0x30, 0x60, 0xC0, 0x90};

void INT_IMIA0(void) {
    ITU0.TSR.BIT.IMFA = 0;      // フラグ初期化
    c += 1;                     // カウントダウン
    if(c < 600){                  // カウントが0以下なら
        PA.DR.BYTE = md[c%4];   // 信号変更
    }
}

void main(void)
{
    int i;
    char str[17];

    // 初期設定
    init_lcd();                 // LCD初期化
    clear_lcd();                // LCD画面リセット
    PA.DDR = 0xf0;              // PA出力モード
    ITU0.TCR.BIT.CCLR = 1;      // カウンタリセット要因
    ITU0.TCR.BIT.TPSC = 3;
    ITU0.GRA = 62499;
    ITU0.TIER.BIT.IMIEA = 1;
    ITU.TSTR.BIT.STR0 = 1;
    
    while(1){
        if(!PA.DR.BIT.B0){
              c = 500;  
        }
        if(!PA.DR.BIT.B1){
              c = 0;  
        }
        
        locate_lcd(0, 0);		// LCD1行目にカーソルを移動
        itoa(c, str);		    // 取り込んだ値を文字列に変換
        lcd_prints(str);        // LCDに文字列を表示
        lcd_prints("   ");      // LCDの不要部分を上書き
    }
}
