/***********************************************************************/
/*                                                                     */
/*  FILE        :task01.c                                               */
/*  DATE        :Mon, Oct 02, 2017                                     */
/*  DESCRIPTION :Main Program                                          */
/*  CPU TYPE    :H8/3052F                                              */
/*                                                                     */
/*  This file is generated by Renesas Project Generator (Ver.4.16).    */
/*                                                                     */
/***********************************************************************/

#include "iodefine.h"
#include "conv.h"
#include "lcd.h"
#include "rsctl.h"

void main(void)
{
	unsigned int i;
	double j;
	char str[10];
	
	// 初期設定
	initSCI1(BR38400);					// ボーレート
	init_lcd();							// LCD初期化
	clear_lcd();
	AD.ADCSR.BYTE = 0x08;				// AN0単一モード
	
	while(1){		
		// アナログ信号取得
		AD.ADCSR.BIT.ADST = 1;			// スキャン開始
		while(AD.ADCSR.BIT.ADF != 1);	// スキャン終了まで待機
		i = AD.ADDRA >> 6;				// 値取り込み
		clear_lcd();
	
		// アナログ信号表示
		locate_lcd(0, 0);				// LCD1行目にカーソルを移動
		itoa(i, str);					// 取り込んだ値を文字列に変換
		lcd_prints(str);				// LCDに文字列を表示
		
		// アナログ信号電圧値変換表示
		j = (double)(i * 5) / 1023;		// 電圧値へ変換
		locate_lcd(0, 1);				// LCD2行目にカーソルを移動
		dtoa(j, 3, str);				// 電圧値を文字列に変換
		lcd_prints(str);				// LCDに文字列を表示
		lcd_prints("V");				// LCDに単位を表示

		// シリアル送信
		btoa(i, str);					// 取り込んだ値を2進数で文字列に変換
		SCI1_OUT_s(str);				// シリアルポートに文字列を送信
		
		// ボタンが押下されるまで待機
		while(PA.DR.BIT.B0);
	}
}
