/***********************************************************************/
/*                                                                     */
/*  FILE        :task04-3.c                                            */
/*  DATE        :Mon, Oct 30, 2017                                     */
/*  DESCRIPTION :Main Program                                          */
/*  CPU TYPE    :H8/3052F                                              */
/*                                                                     */
/*  This file is generated by Renesas Project Generator (Ver.4.16).    */
/*                                                                     */
/***********************************************************************/
#include <string.h>

#include "iodefine.h"
#include "conv.h"
#include "lcd.h"
#include "rsctl.h"

#pragma interrupt INT_IMIA2(vect=32)

int t = 0x80;                   // タイマー
int c = 0x80;                   // カウンター
long period = 0x7FFF;

void INT_IMIA2(void) {
    ITU2.TSR.BIT.IMFA = 0;      // フラグ初期化
    c++;
    period = ITU2.GRA;
}

void main(void)
{
    char str[17];
    double tmp;
    int i, time;
    
    // ポート初期化
    P4.DDR = 0x03;                  // DCモーター IN1, 2
    P4.DR.BYTE = 0x03;              // 初期状態ブレーキ
    
    PA.DDR = 0x00;                  // SW0~4
    
    // インプットキャプチャ初期化
    ITU2.TCR.BIT.CCLR = 1;          // TCNT2はICでクリア
    ITU2.TCR.BIT.TPSC = 3;          // 1/8クロック
    ITU2.TIOR.BIT.IOA = 5;          // 立ち上がりでICを起こす
    ITU2.TIER.BIT.IMIEA = 1;        // GRA2のICで割り込み許可
    
    // LCD初期化
    init_lcd();                     // LCD初期化
    clear_lcd();                    // LCD画面リセット
    
    // タイマースタート
    ITU.TSTR.BIT.STR2 = 1;          // カウンタスタート
    
    // メインループ
    while(1){
    
        P4.DR.BYTE = 0x03;                // DCモーター運転停止
        
        while(PA.DR.BIT.B0 && PA.DR.BIT.B1);// SW0が押されるまで待機
        
        c = 0;                              // カウントリセット
        
        if(!PA.DR.BIT.B0){
            P4.DR.BYTE = 0x02;              // DCモーター前進
            
            while(c < 6000);                // 100mm移動待機
        }
        else if(!PA.DR.BIT.B1){
            P4.DR.BYTE = 0x01;              // DCモーター後退
            
            while(c < 3000);                // 50mm移動待機
        }
    }
}
