/***********************************************************************/
/*                                                                     */
/*  FILE        :task02.c                                               */
/*  DATE        :Mon, Oct 06, 2017                                     */
/*  DESCRIPTION :Main Program                                          */
/*  CPU TYPE    :H8/3052F                                              */
/*                                                                     */
/*  This file is generated by Renesas Project Generator (Ver.4.16).    */
/*                                                                     */
/***********************************************************************/

#include "iodefine.h"
#include "conv.h"
#include "lcd.h"
#include "rsctl.h"

void main(void)
{
    char str[17];
    int now, bak = 0x00;

    // 初期設定
    init_lcd();                         // LCD初期化
    clear_lcd();
    DA.DACR.BIT.DAOE0 = 1;              // DA0使用
    DA.DACR.BIT.DAE = 0;                // チャネル0 DA変換許可

    while(1){
        // 前回値とスイッチの状態
        while((now = PA.DR.BYTE & 0x0F ^ 0x0F) == bak);
        
        // DA0に今回値を出力
        DA.DADR0 = now * 17;
        
        // [デバック用]LCDに今回値表示
        locate_lcd(0, 0);				// LCD1行目にカーソルを移動
        btoa(DA.DADR0, str);		        // 取り込んだ値を文字列に変換
        lcd_prints(str);				// LCDに文字列を表示
        
        // 前回値の更新
        bak = now;
    }
}
