/***********************************************************************/
/*                                                                     */
/*  FILE        :task02.c                                               */
/*  DATE        :Mon, Oct 06, 2017                                     */
/*  DESCRIPTION :Main Program                                          */
/*  CPU TYPE    :H8/3052F                                              */
/*                                                                     */
/*  This file is generated by Renesas Project Generator (Ver.4.16).    */
/*                                                                     */
/***********************************************************************/

#include "iodefine.h"
#include "conv.h"
#include "lcd.h"
#include "rsctl.h"
#pragma interrupt INT_IMIA0(vect=24)

unsigned int c = 0x8fff;
unsigned char md[] = {0x30, 0x60, 0xC0, 0x90};

void main(void)
{
    int i;
    char str[17];

    // 初期設定
    PA.DDR = 0xf0;              // PA出力モード
    
    DMAC0A.MAR = md;            // メモリアドレス転送元
    DMAC0A.IOAR = 0xD3;           // IOアドレス
    DMAC0A.ETCR = 0x0404;       // 転送回数 4回
    DMAC0A.DTCR.BIT.DTSZ = 0;   // バイトサイズ転送
    DMAC0A.DTCR.BIT.DTID = 0;   // 転送後MARをインクリメント
    DMAC0A.DTCR.BIT.RPE = 1;    // リピートモード
    DMAC0A.DTCR.BIT.DTIE = 0;   // リピートモード
    DMAC0A.DTCR.BIT.DTS = 0;    // ITU0コンペアマッチで割り込み
    DMAC0A.DTCR.BIT.DTE = 1;    // データ転送許可
    
    ITU0.TIOR.BIT.IOA = 0;      // コンペアマッチによる出力禁止
    ITU0.GRA = 62499;           // パルス周期 20ms
    ITU0.TCR.BYTE = 0x23;       // GRAコンペアマッチカウンタクリア
                                // TCNTクリアクロック 1/1
    ITU0.TIER.BIT.IMIEA = 1;    // 割り込み許可
    
    init_lcd();                 // LCD初期化
    clear_lcd();                // LCD画面リセット
    
    while(1){
        if(!PA.DR.BIT.B0){
              ITU.TSTR.BIT.STR0 = 1;
        }
        if(!PA.DR.BIT.B1){
              ITU.TSTR.BIT.STR0 = 0; 
        }
    }
}
